### ISSUE TITLE
Quick entry error 500

### ISSUE THREAD

**Issue by janleskovec** [akhilrex/hammond#104]
**Please complete the following information**
 - Installation Type: [Docker]
 - Have you tried using the latest docker image / code base [yes]

**Describe the bug**
The quick entry returns an error 500, when uploading a photo.

**To Reproduce**
1. Go to the homescreen
2. Select Photo
3. Upload File

**Expected behavior**
A quick entry gets added

**Logs**
```
[GIN] 2022/08/30 - 12:52:25 | 500 |   12.813694ms |       10.0.1.27 | POST     "/api/quickEntries"
2022/08/30 12:52:25 [Recovery] 2022/08/30 - 12:52:25 panic recovered:
interface conversion: error is url.EscapeError, not validator.ValidationErrors
/usr/local/go/src/runtime/iface.go:261 (0x412d2b)
/usr/local/go/src/runtime/iface.go:271 (0x412c8f)
/api/common/utils.go:61 (0x9b413b)
/api/controllers/files.go:30 (0x9d7b14)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x9b20f9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0x9b20e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x9ea0ab)
/api/main.go:68 (0x9ea08d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x9b20f9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/recovery.go:99 (0x9b20e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x9b11d3)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/logger.go:241 (0x9b1192)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/context.go:165 (0x9a7989)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:489 (0x9a796f)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.1/gin.go:445 (0x9a745b)
/usr/local/go/src/net/http/server.go:2887 (0x6b5b22)
/usr/local/go/src/net/http/server.go:1952 (0x6b0f4c)
/usr/local/go/src/runtime/asm_amd64.s:1371 (0x473e60)
```

**Additional context**
This is a fresh installation on docker with the following compose file:
```
version: '2.1'
services:
  hammond:
    image: akhilrex/hammond
    container_name: hammond
    volumes:
      - /data/hammond/config:/config
      - /data/hammond/data:/assets
    ports:
      - 8083:3000
    restart: unless-stopped
```
