### ISSUE TITLE
Site does not respond after changing port binding?

### ISSUE THREAD

**Issue by 2600box** [akhilrex/hammond#63]
Hi, I am new to docker, so this is probably a mistake on my part. 

After changing the docker-compose as below, I cannot connect on port 4000.

in `docker ps` there is still a reference to `tcp/3000`

```
752a84b2cd5c   akhilrex/hammond                   "./app"                  3 minutes ago   Up 5 seconds                     3000/tcp, 0.0.0.0:4000->4000/tcp, :::4000->4000/tcp   hammond
```

Do I need to change something else?

Thanks!

 
```
cat docker-compose.yml
version: "2.1"
services:
  hammond:
    image: akhilrex/hammond
    container_name: hammond
    environment:
      - JWT_SECRET = somethingverystrong
    volumes:
      - /home/docker_user/hammond/config:/config
      - /home/docker_user/hammond/data:/assets
    ports:
      - 4000:4000
    restart: unless-stopped
```
